feat: let the client handle the cookies
alphagov/consent-api pull request #204
Opened 2023-11-24 17:16 UTC by guifry

This PR aims at simplifying the user experience of the library, by letting the library handle all the management of the browser cookies. Users of the library will be able to interact with Single Consent via a higher level API, such as class methods, instead of having to parse / write the cookies themselves.

## Changelog

- The constructor now has only one callback. It takes as arguments:
    - the updated consents
    - a boolean flag `consentsPreferencesSet` that is true if the consents have been set
    - an optional error object.
- The API url can be passed to the constructor directly. If not, it will default to the old behaviour of getting it from the HTML tag.
- The Typescript typing has been improved - not perfect yet
- Added methods `getCookie` and `setCookie`
- Added public method `areCookiePreferencesSet`
- Added unit tests for these new methods
- Improved the config class by setting more static config variables such as the cookie names and default lifetimes
- Added methods to get specific consents. e.g `hasConsentedToEssential()` and `hasConsentedToUsage()`

## Examples

Additionally, the examples have been updated.
I've removed `example/utils.js` since that logic is now handled by the library.

2023-11-27 13:17 UTC, nacnudus submitted a review, later dismissed
Some really nice improvements in here.

2023-11-27 13:17 UTC, nacnudus commented on client/src/GovConsentConfig.ts
> +      )
praise: helpful message

2023-11-27 13:26 UTC, andyhd requested changes
This is great 👍 Just one slightly inefficient bit.

2023-11-27 13:26 UTC, andyhd commented on client/src/GovSingleConsent.ts
> +  }
issue: In the frequent case where the calling code wants to know if consent is given for additional cookies (ie all categories), the cookie is parsed multiple times. Could the consent object from the cookie be cached?

2023-11-27 13:26 UTC, andyhd commented on client/src/GovSingleConsent.ts
> +    setCookie(consentsCookieName, value, lifetime)
quibble: These consts seem redundant - they are only used once, immediately after they are defined, and the values are fairly self-documenting.

2023-11-27 13:26 UTC, andyhd commented on client/src/GovSingleConsent.ts
> +    setCookie(cookieName, value.toString(), lifetime)
quibble: same redundant consts

2023-11-27 13:26 UTC, andyhd commented on client/src/GovSingleConsent.ts
> +    setCookie(cookieName, uid, lifetime)
quibble: unnecessary single-use variables

2023-11-27 13:26 UTC, andyhd commented on client/src/GovSingleConsent.ts
> +            )
suggestion: I see these two methods called together at several points in the code - perhaps these could be refactored

2023-11-27 13:26 UTC, andyhd commented on client/src/GovSingleConsent.ts
> +    }
suggestion: perhaps this function should be a method?

2023-11-27 13:26 UTC, andyhd commented on client/src/GovConsentConfig.ts
> +  getApiUrlFromHtml() {
suggestion: I think we can remove this function now that the URL is passed in to the constructor. This was just for testing purposes anyway.

2023-11-27 13:31 UTC, andyhd commented on client/src/GovSingleConsent.ts
> +    setCookie(consentsCookieName, value, lifetime)
suggestion: You could call `setCookie` with an object if you want to be really clear about what each parameter is, eg: `setCookie({cookieName: GovConsentConfig.CONSENTS_COOKIE_NAME, value: JSON.stringify(consents), lifetime: GovConsentConfig.COOKIE_LIFETIME})`

2023-11-29 08:37 UTC, guifry commented on client/src/GovSingleConsent.ts
> +    }
I'd like to refactor this in another PR where I'll separate the http layer from the business logic layer if that's ok

2023-11-29 08:38 UTC, guifry commented on client/src/GovSingleConsent.ts
> +            )
I'd like to refactor this in another PR where I'll separate the http layer from the business logic layer if that's ok

2023-11-29 08:42 UTC, guifry commented on client/src/GovSingleConsent.ts
> +  }
It's a good point. I didn't go with caching initially, because it could lead to a breach of GDPR if the users of the library were to update the cookie value themselves for whatever reason. That change would make the cache out of sync, and those methods wouldn't return accurate booleans.

However if we make it clear in the docs that the users should not modify the cookies themselves and should instead solely rely on the lib, then it's safe. Or at least, we are safe..

I've cached it on the `window` obj

2023-11-29 09:47 UTC, andyhd commented on client/src/GovSingleConsent.ts
> +  }
Thanks, this is good. I imagined that the return value of `getConsents` could be stored in a private attribute of the `GovSingleConsent` object, and written once when parsing the cookie, then read many times by calls to these methods. If the cookie is only set by the `GovSingleConsent` object, then it should override any external changes to the cookie, shouldn't it?

2023-11-29 09:48 UTC, andyhd approved these changes

2023-11-29 09:49 UTC, merged